### Создать категорию
POST http://localhost:8080/admin/categories
Content-Type: application/json

{
  "name": "Музыка"
}

###

### Получить все категории
GET http://localhost:8080/categories

###

### Получить категорию по id
GET http://localhost:8080/categories/1

###

### Обновить категорию
PATCH http://localhost:8080/admin/categories/1
Content-Type: application/json

{
  "id": 1,
  "name": "Концерты"
}

###

### Удалить категорию
DELETE http://localhost:8080/admin/categories/1

###
GET /categories/999
